require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe QuantitiesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Quantity. As you add validations to Quantity, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuantitiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all quantities as @quantities" do
      quantity = Quantity.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:quantities)).to eq([quantity])
    end
  end

  describe "GET #show" do
    it "assigns the requested quantity as @quantity" do
      quantity = Quantity.create! valid_attributes
      get :show, params: {id: quantity.to_param}, session: valid_session
      expect(assigns(:quantity)).to eq(quantity)
    end
  end

  describe "GET #new" do
    it "assigns a new quantity as @quantity" do
      get :new, params: {}, session: valid_session
      expect(assigns(:quantity)).to be_a_new(Quantity)
    end
  end

  describe "GET #edit" do
    it "assigns the requested quantity as @quantity" do
      quantity = Quantity.create! valid_attributes
      get :edit, params: {id: quantity.to_param}, session: valid_session
      expect(assigns(:quantity)).to eq(quantity)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Quantity" do
        expect {
          post :create, params: {quantity: valid_attributes}, session: valid_session
        }.to change(Quantity, :count).by(1)
      end

      it "assigns a newly created quantity as @quantity" do
        post :create, params: {quantity: valid_attributes}, session: valid_session
        expect(assigns(:quantity)).to be_a(Quantity)
        expect(assigns(:quantity)).to be_persisted
      end

      it "redirects to the created quantity" do
        post :create, params: {quantity: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Quantity.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved quantity as @quantity" do
        post :create, params: {quantity: invalid_attributes}, session: valid_session
        expect(assigns(:quantity)).to be_a_new(Quantity)
      end

      it "re-renders the 'new' template" do
        post :create, params: {quantity: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested quantity" do
        quantity = Quantity.create! valid_attributes
        put :update, params: {id: quantity.to_param, quantity: new_attributes}, session: valid_session
        quantity.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested quantity as @quantity" do
        quantity = Quantity.create! valid_attributes
        put :update, params: {id: quantity.to_param, quantity: valid_attributes}, session: valid_session
        expect(assigns(:quantity)).to eq(quantity)
      end

      it "redirects to the quantity" do
        quantity = Quantity.create! valid_attributes
        put :update, params: {id: quantity.to_param, quantity: valid_attributes}, session: valid_session
        expect(response).to redirect_to(quantity)
      end
    end

    context "with invalid params" do
      it "assigns the quantity as @quantity" do
        quantity = Quantity.create! valid_attributes
        put :update, params: {id: quantity.to_param, quantity: invalid_attributes}, session: valid_session
        expect(assigns(:quantity)).to eq(quantity)
      end

      it "re-renders the 'edit' template" do
        quantity = Quantity.create! valid_attributes
        put :update, params: {id: quantity.to_param, quantity: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested quantity" do
      quantity = Quantity.create! valid_attributes
      expect {
        delete :destroy, params: {id: quantity.to_param}, session: valid_session
      }.to change(Quantity, :count).by(-1)
    end

    it "redirects to the quantities list" do
      quantity = Quantity.create! valid_attributes
      delete :destroy, params: {id: quantity.to_param}, session: valid_session
      expect(response).to redirect_to(quantities_url)
    end
  end

end
